import React, { useState } from 'react';
import Head from 'next/head';
import TodoItem from '../components/TodoItem/TodoItem';
import styled from 'styled-components';
import Input from '../components/Input';
import Button from '../components/Button';
import uniqid from 'uniqid';

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [newInput, setNewInput] = useState('');

  const addTodo = () => {
    if (newInput.trim() === '') {
      alert('내용을 입력해주세요');
      return;
    }
    const newTodo = {
      text: newInput,
      id: uniqid(),
      completed: false,
    };
    setTodos((prev) => {
      return [...prev, newTodo];
    });
    setNewInput('');
  };

  const onCompleteClick = (id) => {
    const targetIndex = todos.findIndex((todo) => todo.id === id);
    if (targetIndex === -1) {
      alert('잘못된 id입니다');
      return;
    }
    setTodos((prev) => {
      const newTodo = {
        ...prev[targetIndex],
        completed: !prev[targetIndex].completed,
      };
      let newArr = [...prev];
      newArr.splice(targetIndex, 1, newTodo);
      return newArr;
    });
  };

  return (
    <>
      <Head>
        <title>Simple Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Todo>
          <Title>Simple Todo</Title>
          <TodoListWrapper>
            {todos?.map((todo) => (
              <TodoItem
                key={todo.id}
                id={todo.id}
                text={todo.text}
                completed={todo.completed}
                onCompleteClick={onCompleteClick}
              />
            ))}
          </TodoListWrapper>
          <Input
            value={newInput}
            onChange={(e) => {
              setNewInput(e.target.value);
            }}
          />
          <Button onClick={addTodo}>등록 실행 불가 </Button>
        </Todo>
      </Container>
    </>
  );
}

const Title = styled.h1`
  margin: 0;
  padding: 0;
  border-radius: 30px;
  padding: 25px 15px;
`;
const Todo = styled.div`
  min-width: 280px;
  margin: 10px 0;
  width: 447px;
  box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.16);
  border-radius: 8px;
`;
const Container = styled.main`
  display: flex;
  align-content: center;
  justify-content: center;
  padding: 25px;
`;

const TodoListWrapper = styled.ul`
  display: flex;
  flex-direction: column;
  row-gap: 8px;
  padding: 16px;
`;
