import Head from 'next/head';
import { CheckOutlined, DeleteOutlined, EditOutlined } from '@ant-design/icons';
import styled from "styled-components";
import Add from '../components/Add';
import FormText from '../components/InputText';
 const Title = styled.h1`
    margin: 0;
    padding: 0;
    border-radius: 30px;
    padding: 25px 15px;
  `;


{/* 1/8 컴포넌트 구성은.. 
  * - component
  * - 등록 (상태: default, done, hover)
  * - 수정 
  * - 삭제 
  * 
  * inputText
  * button
  * 
  * template
  *  input + button  
  */}

export default function Home() {
  return (
    <>
        <Head>
          <title>Simple Todo</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Title>Simple Todo</Title>
          
          <FormText />
          <Add />
          
          <CheckOutlined />
          <EditOutlined />
          <DeleteOutlined />
        </main>
    </>
  )
}