import React, { useMemo, useState } from 'react';
import Head from 'next/head';
import TodoItem from '../components/TodoItem/TodoItem';
import styled from 'styled-components';
import Input from '../components/Input';
import Button from '../components/Button';
import useTodos from '../hooks/useTodos';

export default function Home() {
  const { todos, newInput, setNewInput, addTodo } = useTodos();

  const filteredTodo = useMemo(() => {
    return todos.filter((todo) => todo.completed === false);
  }, [todos]);

  return (
    <>
      <Head>
        <title>Simple Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Todo>
          <Title>Simple Todo</Title>
          {filteredTodo.map((todo) => (
            <TodoItem
              key={todo.id}
              id={todo.id}
              text={todo.text}
              completed={todo.completed}
            />
          ))}
          <Input
            value={newInput}
            onChange={(e) => {
              setNewInput(e.target.value);
            }}
          />
          <Button onClick={addTodo}>등록 실행 불가 </Button>
        </Todo>
      </Container>
    </>
  );
}

const Title = styled.h1`
  margin: 0;
  padding: 0;
  border-radius: 30px;
  padding: 25px 15px;
`;
const Todo = styled.div`
  min-width: 280px;
  margin: 10px 0;
  width: 447px;
  height: 522px;
  box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.16);
  border-radius: 8px;
`;
const Container = styled.main`
  display: flex;
  align-content: center;
  justify-content: center;
  padding: 25px;
`;
